### ISSUE TITLE
Overeager detection of imports

### ISSUE THREAD

**Issue by Shadlock0133** [hasherezade/bearparser#11]
I'm making a pe writer and after adding imports, my output file weren't working. I finally found out after comparing it with corkami's `pe101.exe`. 

If file has `.idata` section at raw address 0x200 and at virtual address 0x1000, and import in data directory points at address 0x200, pe-bear shows no warnings and displays imports tab with content. But Windows won't populate import address table, resulting in segfault in most cases.

It might be worthwhile to add warning for this case, though it's not that important.

Also, pe-bear colour codes some fields, but there aren't explained in program. It might be helpful to add mouse-over tooltips for them.

**Comment by Shadlock0133** [comment]
[test.zip](https://github.com/hasherezade/bearparser/files/5595995/test.zip)

**Comment by hasherezade** [comment]
Ok, I fixed it, it should be fine now:

![invalid_va](https://user-images.githubusercontent.com/3115348/100235662-fdea7680-2f2c-11eb-9cc4-feaf0ddef181.png)

This patch will be included in the next release. Thank you very much for reporting!

**Comment by hasherezade** [comment]
If you wish to test the new build before the release, please send me an e-mail: hasherezade@pm.me

**Comment by hasherezade** [comment]
It should be solved in the latest PEbear: https://github.com/hasherezade/pe-bear-releases/releases/tag/0.5.2.3 - please check it out, and if everything is fine, feel free to close this issue.

**Comment by Shadlock0133** [comment]
Works correct now, thanks!
