### ISSUE TITLE
Exception limit is too small for large binaries.

### ISSUE THREAD

**Issue by jonomango** [hasherezade/bearparser#15]
https://github.com/hasherezade/bearparser/blob/6e0a8174a152c12c8521ffc2dc39b5b3b0523c6f/parser/pe/ExceptionDirWrapper.cpp#L4

I think that the current limit for exceptions is too small. Large binaries such as ntoskrnl.exe can have over 30,000 entries while bearparser will only parse the first 10,000. This really caught me off guard while using PE-Bear :sweat_smile:. On a similar note, the number of entries is just `DIRECTORY_SIZE / sizeof(ENTRY)`, so there shouldn't be a need to check for a null-terminator in here:

https://github.com/hasherezade/bearparser/blob/6e0a8174a152c12c8521ffc2dc39b5b3b0523c6f/parser/pe/ExceptionDirWrapper.cpp#L29-L32

...although it does make sense if you're expecting to deal with malformed binaries.

**Comment by hasherezade** [comment]
@jonomango - you are right, I was going to remove those limits, but then I forgot, sorry for this! it is gonna be fixed soon.

**Comment by hasherezade** [comment]
@jonomango - please check the new build (not released yet):

[PE-bear_0.5.5.4_rc1_x64_win_vs17.zip](https://github.com/hasherezade/bearparser/files/8969364/PE-bear_0.5.5.4_rc1_x64_win_vs17.zip)

**Comment by jonomango** [comment]
@hasherezade - Thanks for the quick response! I just tried it out and it works well. It does seem to slow down a bit when scrolling all the way to the bottom, but it's still usable.

**Comment by hasherezade** [comment]
@jonomango - the slowdown in scrolling is unfortunately a thing that cannot be avoided, it always happens when we try to display tables with many rows in Qt. It can be mitigated by introducing pagination. Maybe I will do it in the future, but from what I tested, this slowdown is not that significant to make this urgent.

**Comment by hasherezade** [comment]
@jonomango : the new release is ready: https://github.com/hasherezade/pe-bear-releases/releases/tag/0.5.5.4
thank you for your contribution!
