### ISSUE TITLE
Spelling Mistakes in File Header Characteristics

### ISSUE THREAD

**Issue by Kek5chen** [hasherezade/bearparser#18]
![image](https://user-images.githubusercontent.com/52585984/201776370-86fa1012-5093-4673-ae3f-d8664ab4483c.png)

As you, and I, can see, there are a few spelling mistakes in the File Header Characteristics.

**Comment by Kek5chen** [comment]
Fixed in #17

**Comment by hasherezade** [comment]
Thanks!
