### ISSUE TITLE
Building PE bear

### ISSUE THREAD

**Issue by tathanhdinh** [hasherezade/bearparser#2]
Hello all,

I try to rebuild PE bear from source, unfortunately it seems that only `pecommander` is built. I cannot find the binary with GUI anywhere. Does the source code contain only the command line tool?

Many thanks for any response.

**Comment by hasherezade** [comment]
Hello!
Yes, this is true - the GUI is in another module that is currently not open source. You can download only pre-built binaries (for Windows and for Linux).

**Comment by tathanhdinh** [comment]
Thanks @hasherezade .
