### ISSUE TITLE
Release a new version

### ISSUE THREAD

**Issue by MIvanchev** [hasherezade/bearparser#31]
A lot seems to have changed since a version was last released, maybe time for a new one (and also because I want to make a Void Linux release of PE-bear).

**Comment by hasherezade** [comment]
hi @MIvanchev ! Do you mean a new version of bearparser, or a new version of PE-bear?

**Comment by MIvanchev** [comment]
Hey @hasherezade , I mean bearparser.

**Comment by hasherezade** [comment]
ok @MIvanchev , I added a new release, check it out!

**Comment by MIvanchev** [comment]
Thank you, let's try building :)
